// <auto-generated />
using HoroscopeApplication.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HoroscopeApplication.Migrations
{
    [DbContext(typeof(HoroscopeAppDbContext))]
    [Migration("20211028063228_AddSunsignsTableWithSeedData")]
    partial class AddSunsignsTableWithSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HoroscopeApplication.Models.Sunsign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SunSign")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sunsigns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = "01-01",
                            SunSign = "Capricorn"
                        },
                        new
                        {
                            Id = 2,
                            Date = "02-01",
                            SunSign = "Capricorn"
                        },
                        new
                        {
                            Id = 3,
                            Date = "03-01",
                            SunSign = "Capricorn"
                        },
                        new
                        {
                            Id = 4,
                            Date = "04-01",
                            SunSign = "Capricorn"
                        },
                        new
                        {
                            Id = 5,
                            Date = "05-01",
                            SunSign = "Capricorn"
                        },
                        new
                        {
                            Id = 6,
                            Date = "06-01",
                            SunSign = "Capricorn"
                        },
                        new
                        {
                            Id = 7,
                            Date = "07-01",
                            SunSign = "Capricorn"
                        },
                        new
                        {
                            Id = 8,
                            Date = "08-01",
                            SunSign = "Capricorn"
                        },
                        new
                        {
                            Id = 9,
                            Date = "09-01",
                            SunSign = "Capricorn"
                        },
                        new
                        {
                            Id = 10,
                            Date = "10-01",
                            SunSign = "Capricorn"
                        },
                        new
                        {
                            Id = 11,
                            Date = "11-01",
                            SunSign = "Capricorn"
                        },
                        new
                        {
                            Id = 12,
                            Date = "12-01",
                            SunSign = "Capricorn"
                        },
                        new
                        {
                            Id = 13,
                            Date = "13-01",
                            SunSign = "Capricorn"
                        },
                        new
                        {
                            Id = 14,
                            Date = "14-01",
                            SunSign = "Capricorn"
                        },
                        new
                        {
                            Id = 15,
                            Date = "15-01",
                            SunSign = "Capricorn"
                        },
                        new
                        {
                            Id = 16,
                            Date = "16-01",
                            SunSign = "Capricorn"
                        },
                        new
                        {
                            Id = 17,
                            Date = "17-01",
                            SunSign = "Capricorn"
                        },
                        new
                        {
                            Id = 18,
                            Date = "18-01",
                            SunSign = "Capricorn"
                        },
                        new
                        {
                            Id = 19,
                            Date = "19-01",
                            SunSign = "Capricorn"
                        },
                        new
                        {
                            Id = 20,
                            Date = "20-01",
                            SunSign = "Aquarius"
                        },
                        new
                        {
                            Id = 21,
                            Date = "21-01",
                            SunSign = "Aquarius"
                        },
                        new
                        {
                            Id = 22,
                            Date = "22-01",
                            SunSign = "Aquarius"
                        },
                        new
                        {
                            Id = 23,
                            Date = "23-01",
                            SunSign = "Aquarius"
                        },
                        new
                        {
                            Id = 24,
                            Date = "24-01",
                            SunSign = "Aquarius"
                        },
                        new
                        {
                            Id = 25,
                            Date = "25-01",
                            SunSign = "Aquarius"
                        },
                        new
                        {
                            Id = 26,
                            Date = "26-01",
                            SunSign = "Aquarius"
                        },
                        new
                        {
                            Id = 27,
                            Date = "27-01",
                            SunSign = "Aquarius"
                        },
                        new
                        {
                            Id = 28,
                            Date = "28-01",
                            SunSign = "Aquarius"
                        },
                        new
                        {
                            Id = 29,
                            Date = "29-01",
                            SunSign = "Aquarius"
                        },
                        new
                        {
                            Id = 30,
                            Date = "30-01",
                            SunSign = "Aquarius"
                        },
                        new
                        {
                            Id = 31,
                            Date = "31-01",
                            SunSign = "Aquarius"
                        },
                        new
                        {
                            Id = 32,
                            Date = "01-02",
                            SunSign = "Aquarius"
                        },
                        new
                        {
                            Id = 33,
                            Date = "02-02",
                            SunSign = "Aquarius"
                        },
                        new
                        {
                            Id = 34,
                            Date = "03-02",
                            SunSign = "Aquarius"
                        },
                        new
                        {
                            Id = 35,
                            Date = "04-02",
                            SunSign = "Aquarius"
                        },
                        new
                        {
                            Id = 36,
                            Date = "05-02",
                            SunSign = "Aquarius"
                        },
                        new
                        {
                            Id = 37,
                            Date = "06-02",
                            SunSign = "Aquarius"
                        },
                        new
                        {
                            Id = 38,
                            Date = "07-02",
                            SunSign = "Aquarius"
                        },
                        new
                        {
                            Id = 39,
                            Date = "08-02",
                            SunSign = "Aquarius"
                        },
                        new
                        {
                            Id = 40,
                            Date = "09-02",
                            SunSign = "Aquarius"
                        },
                        new
                        {
                            Id = 41,
                            Date = "10-02",
                            SunSign = "Aquarius"
                        },
                        new
                        {
                            Id = 42,
                            Date = "11-02",
                            SunSign = "Aquarius"
                        },
                        new
                        {
                            Id = 43,
                            Date = "12-02",
                            SunSign = "Aquarius"
                        },
                        new
                        {
                            Id = 44,
                            Date = "13-02",
                            SunSign = "Aquarius"
                        },
                        new
                        {
                            Id = 45,
                            Date = "14-02",
                            SunSign = "Aquarius"
                        },
                        new
                        {
                            Id = 46,
                            Date = "15-02",
                            SunSign = "Aquarius"
                        },
                        new
                        {
                            Id = 47,
                            Date = "16-02",
                            SunSign = "Aquarius"
                        },
                        new
                        {
                            Id = 48,
                            Date = "17-02",
                            SunSign = "Aquarius"
                        },
                        new
                        {
                            Id = 49,
                            Date = "18-02",
                            SunSign = "Aquarius"
                        },
                        new
                        {
                            Id = 50,
                            Date = "19-02",
                            SunSign = "Pisces"
                        },
                        new
                        {
                            Id = 51,
                            Date = "20-02",
                            SunSign = "Pisces"
                        },
                        new
                        {
                            Id = 52,
                            Date = "21-02",
                            SunSign = "Pisces"
                        },
                        new
                        {
                            Id = 53,
                            Date = "22-02",
                            SunSign = "Pisces"
                        },
                        new
                        {
                            Id = 54,
                            Date = "23-02",
                            SunSign = "Pisces"
                        },
                        new
                        {
                            Id = 55,
                            Date = "24-02",
                            SunSign = "Pisces"
                        },
                        new
                        {
                            Id = 56,
                            Date = "25-02",
                            SunSign = "Pisces"
                        },
                        new
                        {
                            Id = 57,
                            Date = "26-02",
                            SunSign = "Pisces"
                        },
                        new
                        {
                            Id = 58,
                            Date = "27-02",
                            SunSign = "Pisces"
                        },
                        new
                        {
                            Id = 59,
                            Date = "28-02",
                            SunSign = "Pisces"
                        },
                        new
                        {
                            Id = 60,
                            Date = "29-02",
                            SunSign = "Pisces"
                        },
                        new
                        {
                            Id = 61,
                            Date = "01-03",
                            SunSign = "Pisces"
                        },
                        new
                        {
                            Id = 62,
                            Date = "02-03",
                            SunSign = "Pisces"
                        },
                        new
                        {
                            Id = 63,
                            Date = "03-03",
                            SunSign = "Pisces"
                        },
                        new
                        {
                            Id = 64,
                            Date = "04-03",
                            SunSign = "Pisces"
                        },
                        new
                        {
                            Id = 65,
                            Date = "05-03",
                            SunSign = "Pisces"
                        },
                        new
                        {
                            Id = 66,
                            Date = "06-03",
                            SunSign = "Pisces"
                        },
                        new
                        {
                            Id = 67,
                            Date = "07-03",
                            SunSign = "Pisces"
                        },
                        new
                        {
                            Id = 68,
                            Date = "08-03",
                            SunSign = "Pisces"
                        },
                        new
                        {
                            Id = 69,
                            Date = "09-03",
                            SunSign = "Pisces"
                        },
                        new
                        {
                            Id = 70,
                            Date = "10-03",
                            SunSign = "Pisces"
                        },
                        new
                        {
                            Id = 71,
                            Date = "11-03",
                            SunSign = "Pisces"
                        },
                        new
                        {
                            Id = 72,
                            Date = "12-03",
                            SunSign = "Pisces"
                        },
                        new
                        {
                            Id = 73,
                            Date = "13-03",
                            SunSign = "Pisces"
                        },
                        new
                        {
                            Id = 74,
                            Date = "14-03",
                            SunSign = "Pisces"
                        },
                        new
                        {
                            Id = 75,
                            Date = "15-03",
                            SunSign = "Pisces"
                        },
                        new
                        {
                            Id = 76,
                            Date = "16-03",
                            SunSign = "Pisces"
                        },
                        new
                        {
                            Id = 77,
                            Date = "17-03",
                            SunSign = "Pisces"
                        },
                        new
                        {
                            Id = 78,
                            Date = "18-03",
                            SunSign = "Pisces"
                        },
                        new
                        {
                            Id = 79,
                            Date = "19-03",
                            SunSign = "Pisces"
                        },
                        new
                        {
                            Id = 80,
                            Date = "20-03",
                            SunSign = "Pisces"
                        },
                        new
                        {
                            Id = 81,
                            Date = "21-03",
                            SunSign = "Aries"
                        },
                        new
                        {
                            Id = 82,
                            Date = "22-03",
                            SunSign = "Aries"
                        },
                        new
                        {
                            Id = 83,
                            Date = "23-03",
                            SunSign = "Aries"
                        },
                        new
                        {
                            Id = 84,
                            Date = "24-03",
                            SunSign = "Aries"
                        },
                        new
                        {
                            Id = 85,
                            Date = "25-03",
                            SunSign = "Aries"
                        },
                        new
                        {
                            Id = 86,
                            Date = "26-03",
                            SunSign = "Aries"
                        },
                        new
                        {
                            Id = 87,
                            Date = "27-03",
                            SunSign = "Aries"
                        },
                        new
                        {
                            Id = 88,
                            Date = "28-03",
                            SunSign = "Aries"
                        },
                        new
                        {
                            Id = 89,
                            Date = "29-03",
                            SunSign = "Aries"
                        },
                        new
                        {
                            Id = 90,
                            Date = "30-03",
                            SunSign = "Aries"
                        },
                        new
                        {
                            Id = 91,
                            Date = "31-03",
                            SunSign = "Aries"
                        },
                        new
                        {
                            Id = 92,
                            Date = "01-04",
                            SunSign = "Aries"
                        },
                        new
                        {
                            Id = 93,
                            Date = "02-04",
                            SunSign = "Aries"
                        },
                        new
                        {
                            Id = 94,
                            Date = "03-04",
                            SunSign = "Aries"
                        },
                        new
                        {
                            Id = 95,
                            Date = "04-04",
                            SunSign = "Aries"
                        },
                        new
                        {
                            Id = 96,
                            Date = "05-04",
                            SunSign = "Aries"
                        },
                        new
                        {
                            Id = 97,
                            Date = "06-04",
                            SunSign = "Aries"
                        },
                        new
                        {
                            Id = 98,
                            Date = "07-04",
                            SunSign = "Aries"
                        },
                        new
                        {
                            Id = 99,
                            Date = "08-04",
                            SunSign = "Aries"
                        },
                        new
                        {
                            Id = 100,
                            Date = "09-04",
                            SunSign = "Aries"
                        },
                        new
                        {
                            Id = 101,
                            Date = "10-04",
                            SunSign = "Aries"
                        },
                        new
                        {
                            Id = 102,
                            Date = "11-04",
                            SunSign = "Aries"
                        },
                        new
                        {
                            Id = 103,
                            Date = "12-04",
                            SunSign = "Aries"
                        },
                        new
                        {
                            Id = 104,
                            Date = "13-04",
                            SunSign = "Aries"
                        },
                        new
                        {
                            Id = 105,
                            Date = "14-04",
                            SunSign = "Aries"
                        },
                        new
                        {
                            Id = 106,
                            Date = "15-04",
                            SunSign = "Aries"
                        },
                        new
                        {
                            Id = 107,
                            Date = "16-04",
                            SunSign = "Aries"
                        },
                        new
                        {
                            Id = 108,
                            Date = "17-04",
                            SunSign = "Aries"
                        },
                        new
                        {
                            Id = 109,
                            Date = "18-04",
                            SunSign = "Aries"
                        },
                        new
                        {
                            Id = 110,
                            Date = "19-04",
                            SunSign = "Aries"
                        },
                        new
                        {
                            Id = 111,
                            Date = "20-04",
                            SunSign = "Taurus"
                        },
                        new
                        {
                            Id = 112,
                            Date = "21-04",
                            SunSign = "Taurus"
                        },
                        new
                        {
                            Id = 113,
                            Date = "22-04",
                            SunSign = "Taurus"
                        },
                        new
                        {
                            Id = 114,
                            Date = "23-04",
                            SunSign = "Taurus"
                        },
                        new
                        {
                            Id = 115,
                            Date = "24-04",
                            SunSign = "Taurus"
                        },
                        new
                        {
                            Id = 116,
                            Date = "25-04",
                            SunSign = "Taurus"
                        },
                        new
                        {
                            Id = 117,
                            Date = "26-04",
                            SunSign = "Taurus"
                        },
                        new
                        {
                            Id = 118,
                            Date = "27-04",
                            SunSign = "Taurus"
                        },
                        new
                        {
                            Id = 119,
                            Date = "28-04",
                            SunSign = "Taurus"
                        },
                        new
                        {
                            Id = 120,
                            Date = "29-04",
                            SunSign = "Taurus"
                        },
                        new
                        {
                            Id = 121,
                            Date = "30-04",
                            SunSign = "Taurus"
                        },
                        new
                        {
                            Id = 122,
                            Date = "01-05",
                            SunSign = "Taurus"
                        },
                        new
                        {
                            Id = 123,
                            Date = "02-05",
                            SunSign = "Taurus"
                        },
                        new
                        {
                            Id = 124,
                            Date = "03-05",
                            SunSign = "Taurus"
                        },
                        new
                        {
                            Id = 125,
                            Date = "04-05",
                            SunSign = "Taurus"
                        },
                        new
                        {
                            Id = 126,
                            Date = "05-05",
                            SunSign = "Taurus"
                        },
                        new
                        {
                            Id = 127,
                            Date = "06-05",
                            SunSign = "Taurus"
                        },
                        new
                        {
                            Id = 128,
                            Date = "07-05",
                            SunSign = "Taurus"
                        },
                        new
                        {
                            Id = 129,
                            Date = "08-05",
                            SunSign = "Taurus"
                        },
                        new
                        {
                            Id = 130,
                            Date = "09-05",
                            SunSign = "Taurus"
                        },
                        new
                        {
                            Id = 131,
                            Date = "10-05",
                            SunSign = "Taurus"
                        },
                        new
                        {
                            Id = 132,
                            Date = "11-05",
                            SunSign = "Taurus"
                        },
                        new
                        {
                            Id = 133,
                            Date = "12-05",
                            SunSign = "Taurus"
                        },
                        new
                        {
                            Id = 134,
                            Date = "13-05",
                            SunSign = "Taurus"
                        },
                        new
                        {
                            Id = 135,
                            Date = "14-05",
                            SunSign = "Taurus"
                        },
                        new
                        {
                            Id = 136,
                            Date = "15-05",
                            SunSign = "Taurus"
                        },
                        new
                        {
                            Id = 137,
                            Date = "16-05",
                            SunSign = "Taurus"
                        },
                        new
                        {
                            Id = 138,
                            Date = "17-05",
                            SunSign = "Taurus"
                        },
                        new
                        {
                            Id = 139,
                            Date = "18-05",
                            SunSign = "Taurus"
                        },
                        new
                        {
                            Id = 140,
                            Date = "19-05",
                            SunSign = "Taurus"
                        },
                        new
                        {
                            Id = 141,
                            Date = "20-05",
                            SunSign = "Taurus"
                        },
                        new
                        {
                            Id = 142,
                            Date = "21-05",
                            SunSign = "Gemini"
                        },
                        new
                        {
                            Id = 143,
                            Date = "22-05",
                            SunSign = "Gemini"
                        },
                        new
                        {
                            Id = 144,
                            Date = "23-05",
                            SunSign = "Gemini"
                        },
                        new
                        {
                            Id = 145,
                            Date = "24-05",
                            SunSign = "Gemini"
                        },
                        new
                        {
                            Id = 146,
                            Date = "25-05",
                            SunSign = "Gemini"
                        },
                        new
                        {
                            Id = 147,
                            Date = "26-05",
                            SunSign = "Gemini"
                        },
                        new
                        {
                            Id = 148,
                            Date = "27-05",
                            SunSign = "Gemini"
                        },
                        new
                        {
                            Id = 149,
                            Date = "28-05",
                            SunSign = "Gemini"
                        },
                        new
                        {
                            Id = 150,
                            Date = "29-05",
                            SunSign = "Gemini"
                        },
                        new
                        {
                            Id = 151,
                            Date = "30-05",
                            SunSign = "Gemini"
                        },
                        new
                        {
                            Id = 152,
                            Date = "31-05",
                            SunSign = "Gemini"
                        },
                        new
                        {
                            Id = 153,
                            Date = "01-06",
                            SunSign = "Gemini"
                        },
                        new
                        {
                            Id = 154,
                            Date = "02-06",
                            SunSign = "Gemini"
                        },
                        new
                        {
                            Id = 155,
                            Date = "03-06",
                            SunSign = "Gemini"
                        },
                        new
                        {
                            Id = 156,
                            Date = "04-06",
                            SunSign = "Gemini"
                        },
                        new
                        {
                            Id = 157,
                            Date = "05-06",
                            SunSign = "Gemini"
                        },
                        new
                        {
                            Id = 158,
                            Date = "06-06",
                            SunSign = "Gemini"
                        },
                        new
                        {
                            Id = 159,
                            Date = "07-06",
                            SunSign = "Gemini"
                        },
                        new
                        {
                            Id = 160,
                            Date = "08-06",
                            SunSign = "Gemini"
                        },
                        new
                        {
                            Id = 161,
                            Date = "09-06",
                            SunSign = "Gemini"
                        },
                        new
                        {
                            Id = 162,
                            Date = "10-06",
                            SunSign = "Gemini"
                        },
                        new
                        {
                            Id = 163,
                            Date = "11-06",
                            SunSign = "Gemini"
                        },
                        new
                        {
                            Id = 164,
                            Date = "12-06",
                            SunSign = "Gemini"
                        },
                        new
                        {
                            Id = 165,
                            Date = "13-06",
                            SunSign = "Gemini"
                        },
                        new
                        {
                            Id = 166,
                            Date = "14-06",
                            SunSign = "Gemini"
                        },
                        new
                        {
                            Id = 167,
                            Date = "15-06",
                            SunSign = "Gemini"
                        },
                        new
                        {
                            Id = 168,
                            Date = "16-06",
                            SunSign = "Gemini"
                        },
                        new
                        {
                            Id = 169,
                            Date = "17-06",
                            SunSign = "Gemini"
                        },
                        new
                        {
                            Id = 170,
                            Date = "18-06",
                            SunSign = "Gemini"
                        },
                        new
                        {
                            Id = 171,
                            Date = "19-06",
                            SunSign = "Gemini"
                        },
                        new
                        {
                            Id = 172,
                            Date = "20-06",
                            SunSign = "Gemini"
                        },
                        new
                        {
                            Id = 173,
                            Date = "21-06",
                            SunSign = "Cancer"
                        },
                        new
                        {
                            Id = 174,
                            Date = "22-06",
                            SunSign = "Cancer"
                        },
                        new
                        {
                            Id = 175,
                            Date = "23-06",
                            SunSign = "Cancer"
                        },
                        new
                        {
                            Id = 176,
                            Date = "24-06",
                            SunSign = "Cancer"
                        },
                        new
                        {
                            Id = 177,
                            Date = "25-06",
                            SunSign = "Cancer"
                        },
                        new
                        {
                            Id = 178,
                            Date = "26-06",
                            SunSign = "Cancer"
                        },
                        new
                        {
                            Id = 179,
                            Date = "27-06",
                            SunSign = "Cancer"
                        },
                        new
                        {
                            Id = 180,
                            Date = "28-06",
                            SunSign = "Cancer"
                        },
                        new
                        {
                            Id = 181,
                            Date = "29-06",
                            SunSign = "Cancer"
                        },
                        new
                        {
                            Id = 182,
                            Date = "30-06",
                            SunSign = "Cancer"
                        },
                        new
                        {
                            Id = 183,
                            Date = "01-07",
                            SunSign = "Cancer"
                        },
                        new
                        {
                            Id = 184,
                            Date = "02-07",
                            SunSign = "Cancer"
                        },
                        new
                        {
                            Id = 185,
                            Date = "03-07",
                            SunSign = "Cancer"
                        },
                        new
                        {
                            Id = 186,
                            Date = "04-07",
                            SunSign = "Cancer"
                        },
                        new
                        {
                            Id = 187,
                            Date = "05-07",
                            SunSign = "Cancer"
                        },
                        new
                        {
                            Id = 188,
                            Date = "06-07",
                            SunSign = "Cancer"
                        },
                        new
                        {
                            Id = 189,
                            Date = "07-07",
                            SunSign = "Cancer"
                        },
                        new
                        {
                            Id = 190,
                            Date = "08-07",
                            SunSign = "Cancer"
                        },
                        new
                        {
                            Id = 191,
                            Date = "09-07",
                            SunSign = "Cancer"
                        },
                        new
                        {
                            Id = 192,
                            Date = "10-07",
                            SunSign = "Cancer"
                        },
                        new
                        {
                            Id = 193,
                            Date = "11-07",
                            SunSign = "Cancer"
                        },
                        new
                        {
                            Id = 194,
                            Date = "12-07",
                            SunSign = "Cancer"
                        },
                        new
                        {
                            Id = 195,
                            Date = "13-07",
                            SunSign = "Cancer"
                        },
                        new
                        {
                            Id = 196,
                            Date = "14-07",
                            SunSign = "Cancer"
                        },
                        new
                        {
                            Id = 197,
                            Date = "15-07",
                            SunSign = "Cancer"
                        },
                        new
                        {
                            Id = 198,
                            Date = "16-07",
                            SunSign = "Cancer"
                        },
                        new
                        {
                            Id = 199,
                            Date = "17-07",
                            SunSign = "Cancer"
                        },
                        new
                        {
                            Id = 200,
                            Date = "18-07",
                            SunSign = "Cancer"
                        },
                        new
                        {
                            Id = 201,
                            Date = "19-07",
                            SunSign = "Cancer"
                        },
                        new
                        {
                            Id = 202,
                            Date = "20-07",
                            SunSign = "Cancer"
                        },
                        new
                        {
                            Id = 203,
                            Date = "21-07",
                            SunSign = "Cancer"
                        },
                        new
                        {
                            Id = 204,
                            Date = "22-07",
                            SunSign = "Cancer"
                        },
                        new
                        {
                            Id = 205,
                            Date = "23-07",
                            SunSign = "Leo"
                        },
                        new
                        {
                            Id = 206,
                            Date = "24-07",
                            SunSign = "Leo"
                        },
                        new
                        {
                            Id = 207,
                            Date = "25-07",
                            SunSign = "Leo"
                        },
                        new
                        {
                            Id = 208,
                            Date = "26-07",
                            SunSign = "Leo"
                        },
                        new
                        {
                            Id = 209,
                            Date = "27-07",
                            SunSign = "Leo"
                        },
                        new
                        {
                            Id = 210,
                            Date = "28-07",
                            SunSign = "Leo"
                        },
                        new
                        {
                            Id = 211,
                            Date = "29-07",
                            SunSign = "Leo"
                        },
                        new
                        {
                            Id = 212,
                            Date = "30-07",
                            SunSign = "Leo"
                        },
                        new
                        {
                            Id = 213,
                            Date = "31-07",
                            SunSign = "Leo"
                        },
                        new
                        {
                            Id = 214,
                            Date = "01-08",
                            SunSign = "Leo"
                        },
                        new
                        {
                            Id = 215,
                            Date = "02-08",
                            SunSign = "Leo"
                        },
                        new
                        {
                            Id = 216,
                            Date = "03-08",
                            SunSign = "Leo"
                        },
                        new
                        {
                            Id = 217,
                            Date = "04-08",
                            SunSign = "Leo"
                        },
                        new
                        {
                            Id = 218,
                            Date = "05-08",
                            SunSign = "Leo"
                        },
                        new
                        {
                            Id = 219,
                            Date = "06-08",
                            SunSign = "Leo"
                        },
                        new
                        {
                            Id = 220,
                            Date = "07-08",
                            SunSign = "Leo"
                        },
                        new
                        {
                            Id = 221,
                            Date = "08-08",
                            SunSign = "Leo"
                        },
                        new
                        {
                            Id = 222,
                            Date = "09-08",
                            SunSign = "Leo"
                        },
                        new
                        {
                            Id = 223,
                            Date = "10-08",
                            SunSign = "Leo"
                        },
                        new
                        {
                            Id = 224,
                            Date = "11-08",
                            SunSign = "Leo"
                        },
                        new
                        {
                            Id = 225,
                            Date = "12-08",
                            SunSign = "Leo"
                        },
                        new
                        {
                            Id = 226,
                            Date = "13-08",
                            SunSign = "Leo"
                        },
                        new
                        {
                            Id = 227,
                            Date = "14-08",
                            SunSign = "Leo"
                        },
                        new
                        {
                            Id = 228,
                            Date = "15-08",
                            SunSign = "Leo"
                        },
                        new
                        {
                            Id = 229,
                            Date = "16-08",
                            SunSign = "Leo"
                        },
                        new
                        {
                            Id = 230,
                            Date = "17-08",
                            SunSign = "Leo"
                        },
                        new
                        {
                            Id = 231,
                            Date = "18-08",
                            SunSign = "Leo"
                        },
                        new
                        {
                            Id = 232,
                            Date = "19-08",
                            SunSign = "Leo"
                        },
                        new
                        {
                            Id = 233,
                            Date = "20-08",
                            SunSign = "Leo"
                        },
                        new
                        {
                            Id = 234,
                            Date = "21-08",
                            SunSign = "Leo"
                        },
                        new
                        {
                            Id = 235,
                            Date = "22-08",
                            SunSign = "Leo"
                        },
                        new
                        {
                            Id = 236,
                            Date = "23-08",
                            SunSign = "Virgo"
                        },
                        new
                        {
                            Id = 237,
                            Date = "24-08",
                            SunSign = "Virgo"
                        },
                        new
                        {
                            Id = 238,
                            Date = "25-08",
                            SunSign = "Virgo"
                        },
                        new
                        {
                            Id = 239,
                            Date = "26-08",
                            SunSign = "Virgo"
                        },
                        new
                        {
                            Id = 240,
                            Date = "27-08",
                            SunSign = "Virgo"
                        },
                        new
                        {
                            Id = 241,
                            Date = "28-08",
                            SunSign = "Virgo"
                        },
                        new
                        {
                            Id = 242,
                            Date = "29-08",
                            SunSign = "Virgo"
                        },
                        new
                        {
                            Id = 243,
                            Date = "30-08",
                            SunSign = "Virgo"
                        },
                        new
                        {
                            Id = 244,
                            Date = "31-08",
                            SunSign = "Virgo"
                        },
                        new
                        {
                            Id = 245,
                            Date = "01-09",
                            SunSign = "Virgo"
                        },
                        new
                        {
                            Id = 246,
                            Date = "02-09",
                            SunSign = "Virgo"
                        },
                        new
                        {
                            Id = 247,
                            Date = "03-09",
                            SunSign = "Virgo"
                        },
                        new
                        {
                            Id = 248,
                            Date = "04-09",
                            SunSign = "Virgo"
                        },
                        new
                        {
                            Id = 249,
                            Date = "05-09",
                            SunSign = "Virgo"
                        },
                        new
                        {
                            Id = 250,
                            Date = "06-09",
                            SunSign = "Virgo"
                        },
                        new
                        {
                            Id = 251,
                            Date = "07-09",
                            SunSign = "Virgo"
                        },
                        new
                        {
                            Id = 252,
                            Date = "08-09",
                            SunSign = "Virgo"
                        },
                        new
                        {
                            Id = 253,
                            Date = "09-09",
                            SunSign = "Virgo"
                        },
                        new
                        {
                            Id = 254,
                            Date = "10-09",
                            SunSign = "Virgo"
                        },
                        new
                        {
                            Id = 255,
                            Date = "11-09",
                            SunSign = "Virgo"
                        },
                        new
                        {
                            Id = 256,
                            Date = "12-09",
                            SunSign = "Virgo"
                        },
                        new
                        {
                            Id = 257,
                            Date = "13-09",
                            SunSign = "Virgo"
                        },
                        new
                        {
                            Id = 258,
                            Date = "14-09",
                            SunSign = "Virgo"
                        },
                        new
                        {
                            Id = 259,
                            Date = "15-09",
                            SunSign = "Virgo"
                        },
                        new
                        {
                            Id = 260,
                            Date = "16-09",
                            SunSign = "Virgo"
                        },
                        new
                        {
                            Id = 261,
                            Date = "17-09",
                            SunSign = "Virgo"
                        },
                        new
                        {
                            Id = 262,
                            Date = "18-09",
                            SunSign = "Virgo"
                        },
                        new
                        {
                            Id = 263,
                            Date = "19-09",
                            SunSign = "Virgo"
                        },
                        new
                        {
                            Id = 264,
                            Date = "20-09",
                            SunSign = "Virgo"
                        },
                        new
                        {
                            Id = 265,
                            Date = "21-09",
                            SunSign = "Virgo"
                        },
                        new
                        {
                            Id = 266,
                            Date = "22-09",
                            SunSign = "Virgo"
                        },
                        new
                        {
                            Id = 267,
                            Date = "23-09",
                            SunSign = "Libra"
                        },
                        new
                        {
                            Id = 268,
                            Date = "24-09",
                            SunSign = "Libra"
                        },
                        new
                        {
                            Id = 269,
                            Date = "25-09",
                            SunSign = "Libra"
                        },
                        new
                        {
                            Id = 270,
                            Date = "26-09",
                            SunSign = "Libra"
                        },
                        new
                        {
                            Id = 271,
                            Date = "27-09",
                            SunSign = "Libra"
                        },
                        new
                        {
                            Id = 272,
                            Date = "28-09",
                            SunSign = "Libra"
                        },
                        new
                        {
                            Id = 273,
                            Date = "29-09",
                            SunSign = "Libra"
                        },
                        new
                        {
                            Id = 274,
                            Date = "30-09",
                            SunSign = "Libra"
                        },
                        new
                        {
                            Id = 275,
                            Date = "01-10",
                            SunSign = "Libra"
                        },
                        new
                        {
                            Id = 276,
                            Date = "02-10",
                            SunSign = "Libra"
                        },
                        new
                        {
                            Id = 277,
                            Date = "03-10",
                            SunSign = "Libra"
                        },
                        new
                        {
                            Id = 278,
                            Date = "04-10",
                            SunSign = "Libra"
                        },
                        new
                        {
                            Id = 279,
                            Date = "05-10",
                            SunSign = "Libra"
                        },
                        new
                        {
                            Id = 280,
                            Date = "06-10",
                            SunSign = "Libra"
                        },
                        new
                        {
                            Id = 281,
                            Date = "07-10",
                            SunSign = "Libra"
                        },
                        new
                        {
                            Id = 282,
                            Date = "08-10",
                            SunSign = "Libra"
                        },
                        new
                        {
                            Id = 283,
                            Date = "09-10",
                            SunSign = "Libra"
                        },
                        new
                        {
                            Id = 284,
                            Date = "10-10",
                            SunSign = "Libra"
                        },
                        new
                        {
                            Id = 285,
                            Date = "11-10",
                            SunSign = "Libra"
                        },
                        new
                        {
                            Id = 286,
                            Date = "12-10",
                            SunSign = "Libra"
                        },
                        new
                        {
                            Id = 287,
                            Date = "13-10",
                            SunSign = "Libra"
                        },
                        new
                        {
                            Id = 288,
                            Date = "14-10",
                            SunSign = "Libra"
                        },
                        new
                        {
                            Id = 289,
                            Date = "15-10",
                            SunSign = "Libra"
                        },
                        new
                        {
                            Id = 290,
                            Date = "16-10",
                            SunSign = "Libra"
                        },
                        new
                        {
                            Id = 291,
                            Date = "17-10",
                            SunSign = "Libra"
                        },
                        new
                        {
                            Id = 292,
                            Date = "18-10",
                            SunSign = "Libra"
                        },
                        new
                        {
                            Id = 293,
                            Date = "19-10",
                            SunSign = "Libra"
                        },
                        new
                        {
                            Id = 294,
                            Date = "20-10",
                            SunSign = "Libra"
                        },
                        new
                        {
                            Id = 295,
                            Date = "21-10",
                            SunSign = "Libra"
                        },
                        new
                        {
                            Id = 296,
                            Date = "22-10",
                            SunSign = "Libra"
                        },
                        new
                        {
                            Id = 297,
                            Date = "23-10",
                            SunSign = "Scorpio"
                        },
                        new
                        {
                            Id = 298,
                            Date = "24-10",
                            SunSign = "Scorpio"
                        },
                        new
                        {
                            Id = 299,
                            Date = "25-10",
                            SunSign = "Scorpio"
                        },
                        new
                        {
                            Id = 300,
                            Date = "26-10",
                            SunSign = "Scorpio"
                        },
                        new
                        {
                            Id = 301,
                            Date = "27-10",
                            SunSign = "Scorpio"
                        },
                        new
                        {
                            Id = 302,
                            Date = "28-10",
                            SunSign = "Scorpio"
                        },
                        new
                        {
                            Id = 303,
                            Date = "29-10",
                            SunSign = "Scorpio"
                        },
                        new
                        {
                            Id = 304,
                            Date = "30-10",
                            SunSign = "Scorpio"
                        },
                        new
                        {
                            Id = 305,
                            Date = "31-10",
                            SunSign = "Scorpio"
                        },
                        new
                        {
                            Id = 306,
                            Date = "01-11",
                            SunSign = "Scorpio"
                        },
                        new
                        {
                            Id = 307,
                            Date = "02-11",
                            SunSign = "Scorpio"
                        },
                        new
                        {
                            Id = 308,
                            Date = "03-11",
                            SunSign = "Scorpio"
                        },
                        new
                        {
                            Id = 309,
                            Date = "04-11",
                            SunSign = "Scorpio"
                        },
                        new
                        {
                            Id = 310,
                            Date = "05-11",
                            SunSign = "Scorpio"
                        },
                        new
                        {
                            Id = 311,
                            Date = "06-11",
                            SunSign = "Scorpio"
                        },
                        new
                        {
                            Id = 312,
                            Date = "07-11",
                            SunSign = "Scorpio"
                        },
                        new
                        {
                            Id = 313,
                            Date = "08-11",
                            SunSign = "Scorpio"
                        },
                        new
                        {
                            Id = 314,
                            Date = "09-11",
                            SunSign = "Scorpio"
                        },
                        new
                        {
                            Id = 315,
                            Date = "10-11",
                            SunSign = "Scorpio"
                        },
                        new
                        {
                            Id = 316,
                            Date = "11-11",
                            SunSign = "Scorpio"
                        },
                        new
                        {
                            Id = 317,
                            Date = "12-11",
                            SunSign = "Scorpio"
                        },
                        new
                        {
                            Id = 318,
                            Date = "13-11",
                            SunSign = "Scorpio"
                        },
                        new
                        {
                            Id = 319,
                            Date = "14-11",
                            SunSign = "Scorpio"
                        },
                        new
                        {
                            Id = 320,
                            Date = "15-11",
                            SunSign = "Scorpio"
                        },
                        new
                        {
                            Id = 321,
                            Date = "16-11",
                            SunSign = "Scorpio"
                        },
                        new
                        {
                            Id = 322,
                            Date = "17-11",
                            SunSign = "Scorpio"
                        },
                        new
                        {
                            Id = 323,
                            Date = "18-11",
                            SunSign = "Scorpio"
                        },
                        new
                        {
                            Id = 324,
                            Date = "19-11",
                            SunSign = "Scorpio"
                        },
                        new
                        {
                            Id = 325,
                            Date = "20-11",
                            SunSign = "Scorpio"
                        },
                        new
                        {
                            Id = 326,
                            Date = "21-11",
                            SunSign = "Scorpio"
                        },
                        new
                        {
                            Id = 327,
                            Date = "22-11",
                            SunSign = "Sagittarius"
                        },
                        new
                        {
                            Id = 328,
                            Date = "23-11",
                            SunSign = "Sagittarius"
                        },
                        new
                        {
                            Id = 329,
                            Date = "24-11",
                            SunSign = "Sagittarius"
                        },
                        new
                        {
                            Id = 330,
                            Date = "25-11",
                            SunSign = "Sagittarius"
                        },
                        new
                        {
                            Id = 331,
                            Date = "26-11",
                            SunSign = "Sagittarius"
                        },
                        new
                        {
                            Id = 332,
                            Date = "27-11",
                            SunSign = "Sagittarius"
                        },
                        new
                        {
                            Id = 333,
                            Date = "28-11",
                            SunSign = "Sagittarius"
                        },
                        new
                        {
                            Id = 334,
                            Date = "29-11",
                            SunSign = "Sagittarius"
                        },
                        new
                        {
                            Id = 335,
                            Date = "30-11",
                            SunSign = "Sagittarius"
                        },
                        new
                        {
                            Id = 336,
                            Date = "01-12",
                            SunSign = "Sagittarius"
                        },
                        new
                        {
                            Id = 337,
                            Date = "02-12",
                            SunSign = "Sagittarius"
                        },
                        new
                        {
                            Id = 338,
                            Date = "03-12",
                            SunSign = "Sagittarius"
                        },
                        new
                        {
                            Id = 339,
                            Date = "04-12",
                            SunSign = "Sagittarius"
                        },
                        new
                        {
                            Id = 340,
                            Date = "05-12",
                            SunSign = "Sagittarius"
                        },
                        new
                        {
                            Id = 341,
                            Date = "06-12",
                            SunSign = "Sagittarius"
                        },
                        new
                        {
                            Id = 342,
                            Date = "07-12",
                            SunSign = "Sagittarius"
                        },
                        new
                        {
                            Id = 343,
                            Date = "08-12",
                            SunSign = "Sagittarius"
                        },
                        new
                        {
                            Id = 344,
                            Date = "09-12",
                            SunSign = "Sagittarius"
                        },
                        new
                        {
                            Id = 345,
                            Date = "10-12",
                            SunSign = "Sagittarius"
                        },
                        new
                        {
                            Id = 346,
                            Date = "11-12",
                            SunSign = "Sagittarius"
                        },
                        new
                        {
                            Id = 347,
                            Date = "12-12",
                            SunSign = "Sagittarius"
                        },
                        new
                        {
                            Id = 348,
                            Date = "13-12",
                            SunSign = "Sagittarius"
                        },
                        new
                        {
                            Id = 349,
                            Date = "14-12",
                            SunSign = "Sagittarius"
                        },
                        new
                        {
                            Id = 350,
                            Date = "15-12",
                            SunSign = "Sagittarius"
                        },
                        new
                        {
                            Id = 351,
                            Date = "16-12",
                            SunSign = "Sagittarius"
                        },
                        new
                        {
                            Id = 352,
                            Date = "17-12",
                            SunSign = "Sagittarius"
                        },
                        new
                        {
                            Id = 353,
                            Date = "18-12",
                            SunSign = "Sagittarius"
                        },
                        new
                        {
                            Id = 354,
                            Date = "19-12",
                            SunSign = "Sagittarius"
                        },
                        new
                        {
                            Id = 355,
                            Date = "20-12",
                            SunSign = "Sagittarius"
                        },
                        new
                        {
                            Id = 356,
                            Date = "21-12",
                            SunSign = "Sagittarius"
                        },
                        new
                        {
                            Id = 357,
                            Date = "22-12",
                            SunSign = "Capricorn"
                        },
                        new
                        {
                            Id = 358,
                            Date = "23-12",
                            SunSign = "Capricorn"
                        },
                        new
                        {
                            Id = 359,
                            Date = "24-12",
                            SunSign = "Capricorn"
                        },
                        new
                        {
                            Id = 360,
                            Date = "25-12",
                            SunSign = "Capricorn"
                        },
                        new
                        {
                            Id = 361,
                            Date = "26-12",
                            SunSign = "Capricorn"
                        },
                        new
                        {
                            Id = 362,
                            Date = "27-12",
                            SunSign = "Capricorn"
                        },
                        new
                        {
                            Id = 363,
                            Date = "28-12",
                            SunSign = "Capricorn"
                        },
                        new
                        {
                            Id = 364,
                            Date = "29-12",
                            SunSign = "Capricorn"
                        },
                        new
                        {
                            Id = 365,
                            Date = "30-12",
                            SunSign = "Capricorn"
                        },
                        new
                        {
                            Id = 366,
                            Date = "31-12",
                            SunSign = "Capricorn"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
